### ISSUE TITLE
Disponibilizar label de data pre definida

### ISSUE THREAD

**Issue by LuisPGuimaraes** [TechHorizonBR/API_4SEM_FRONT#28]
PRAZO: 04/10

O QUE FAZER: Preicisa inserir o campo de data pré definida no front no modelo de data com uma data de inicio e fim.
Opções que serão disponibilizadas para o usuário:
* Ontem
* Hoje
* Uma semana
* Um mês
* Um ano
Se tiver ideias, manda no grupo pq só pensei nessas
Precisa retornar este padrão ' 12/09/2024 - 23/02/2024' para ficar mais facil do front tratar

**Comment by santosjhony12** [comment]
Issue has been resolved
