### ISSUE TITLE
Melhorias - Sprint 2

### ISSUE THREAD

**Issue by santosjhony12** [TechHorizonBR/API_4SEM_FRONT#61]
- Adicionar o zoom com o clique
- Adicionar clique na imagem do logo e redenrizar o mapa com o zoom
- Pontos - todos os usuários terão somente uma cor (SelectedUser - roxo) 
- Verde - Inicio
- Amarelo - Parado
- Vermelho - Fim
- Só teremos pontos em Inicio/Parado/Fim

**Comment by vitoriabrancatti** [comment]
- Clique na imagem do logo e renderizar o mapa com o zoom: finalizado 25/10.
- Zoom com o clique:
